### ISSUE TITLE
Help and Doubt About Font Usage | Ajuda e dúvida sobre uso de fonte

### ISSUE THREAD

**Issue by lyovalois** [Meritamen/kanagawa-theme#1]
Primeiramente, gostaria de agradecer pelo seu excelente trabalho na criação desse tema. Estou maravilhado com a estética e a funcionalidade que ele proporciona ao Emacs.

Como iniciante no uso do Emacs, gostaria de pedir sua ajuda para identificar a fonte usada no tema. A escolha da fonte é fundamental para mim, e adoraria replicá-la em meu próprio ambiente Emacs. Vide imagem abaixo.

![Screenshot from 2023-10-08 17-39-39](https://github.com/Meritamen/kanagawa-theme/assets/8315142/ab75e13b-f6aa-4a2b-8f36-8cc09c088cda)

Agradeço muito sua paciência e apoio enquanto continuo a explorar e personalizar o Emacs com a sua criação excepcional.

-----

Firstly, I would like to express my gratitude for your excellent work in creating this theme. I am amazed by the aesthetics and functionality it brings to Emacs.

As a newcomer to Emacs, I would like to ask for your assistance in identifying the font used in the theme. Font choice is crucial to me, and I would love to replicate it in my own Emacs environment. Please see the image below for reference.

![Screenshot from 2023-10-08 17-39-39](https://github.com/Meritamen/kanagawa-theme/assets/8315142/ab75e13b-f6aa-4a2b-8f36-8cc09c088cda)

I greatly appreciate your patience and support as I continue to explore and customize Emacs with your exceptional creation.

**Comment by Meritamen** [comment]
Hello! Thanks for your support. The font is [MonoLisa](https://www.monolisa.dev/).
