### ISSUE TITLE
Publish it on MELPA?

### ISSUE THREAD

**Issue by greydot** [Meritamen/kanagawa-theme#2]
Ohai!

Having this theme on MELPA would greatly ease its installation. Thanks!

**Comment by Meritamen** [comment]
Hello! I've created a pull request to MELPA.

**Comment by greydot** [comment]
https://github.com/melpa/melpa/pull/8789
Linking it here for future reference.

**Comment by Meritamen** [comment]
Now this theme is on MELPA.

**Comment by greydot** [comment]
Great! Thank you!
