### ISSUE TITLE
set-face-attribute: Wrong type argument: stringp, autumn-red

### ISSUE THREAD

**Issue by Ektaynot** [meritamen/kanagawa-theme#3]
Hi, love the theme. I am fairly new to emacs. I've used this theme for about a week and really liked it. But after i updated my doom it broke. It gives me this error when i try to activate the theme. Is there any way you can help? 

set-face-attribute: Wrong type argument: stringp, autumn-red

**Comment by Ektaynot** [comment]
happy to provide any log needed.

**Comment by meritamen** [comment]
Hello, @Ektaynot - Sorry for the late reply

Just fixed this issue, and thanks for your appreciation.:)
